<template>
  <div class="loader-background" v-if="!isLoaded">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      style="
        margin: auto;
        background: none;
        display: block;
        shape-rendering: auto;
      "
      width="128px"
      height="128px"
      viewBox="0 0 100 100"
      preserveAspectRatio="xMidYMid"
      class="position-absolute top-50 start-50 translate-middle"
    >
      <path
        fill="none"
        stroke="#ffffff"
        stroke-width="8"
        stroke-dasharray="42.76482137044271 42.76482137044271"
        d="M24.3 30C11.4 30 5 43.3 5 50s6.4 20 19.3 20c19.3 0 32.1-40 51.4-40 C88.6 30 95 43.3 95 50s-6.4 20-19.3 20C56.4 70 43.6 30 24.3 30z"
        stroke-linecap="round"
        style="transform: scale(0.6); transform-origin: 50px 50px"
      >
        <animate
          attributeName="stroke-dashoffset"
          repeatCount="indefinite"
          dur="2.564102564102564s"
          keyTimes="0;1"
          values="0;256.58892822265625"
        ></animate>
      </path>
      <!-- [ldio] generated by https://loading.io/ -->
    </svg>
  </div>
</template>

<script>
export default {
  data: () => {
    return {
      isLoaded: false,
    };
  },
  methods: {
    changeLoadedState() {
      this.isLoaded = true;
    },
  },
  mounted() {
    document.onreadystatechange = () => {
      if (document.readyState == "complete") {
        setTimeout(this.changeLoadedState, 3000);
      }
    };
  },
};
</script>

<style scoped>
.loader-background {
  position: fixed;
  width: 100vw;
  height: 100vh;
  background: #050b12;
  z-index: 500;
}
</style>